spring.application.name=schneaggchatv3server

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.data.mongodb.database=db
spring.data.mongodb.auto-index-creation=true

logging.level.org.springframework.web=DEBUG

logging.level.org.springframework.core.env=DEBUG
logging.level.org.springframework.boot.context.config=DEBUG

jwt.secret=${JWT_SECRET}

defaultaccount.password=${DEFAULTACCOUNT_PASSWORD}